In [1]:
%pylab
%matplotlib inline
import healpy as hp

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [2]:
T_Hmap = hp.read_map("lambda_haslam408_dsds.fits")   #Haslam Map

NSIDE = 512
ORDERING = NESTED in fits file
INDXSCHM = IMPLICIT


/Users/michellemora/anaconda3/lib/python3.6/site-packages/healpy/fitsfunc.py:371: UserWarning: No INDXSCHM keyword in header file : assume IMPLICIT
  warnings.warn("No INDXSCHM keyword in header file : " "assume {}".format(schm))


Ordering converted to RING


In [8]:
savetxt('T_Hmap.txt', T_Hmap)

## Getting the galactic longitude (l) and latitude (b) from the Haslam Map

In [3]:
nside = hp.get_nside(T_Hmap)  #nside
npix = hp.nside2npix(nside)   #number of pixels

l, b = hp.pix2ang(nside, arange(npix), lonlat=True)   #(l, b) coordinates for each pixel
l,b

(array([ 45., 135., 225., ..., 135., 225., 315.]),
 array([ 89.90862927,  89.90862927,  89.90862927, ..., -89.90862927,
        -89.90862927, -89.90862927]))

In [4]:
gal_lb=column_stack((l,b))    #Galactic coordinates of Haslam Map
gal_lb

array([[ 45.        ,  89.90862927],
       [135.        ,  89.90862927],
       [225.        ,  89.90862927],
       ...,
       [135.        , -89.90862927],
       [225.        , -89.90862927],
       [315.        , -89.90862927]])

In [5]:
#gal_lb[:,0] is going to return the longitude
#gal_lb[:,1] is going to return the latitude

In [6]:
savetxt('GalCoord_HaslamMap.txt', gal_lb)

## Healpy Data

In [7]:
nside,npix,shape(gal_lb)

(512, 3145728, (3145728, 2))